language: python
before_install:
  - npm install gulp
install:
  - pip install -r requirements/local.txt
  - pip install coveralls
  - npm install
  - python manage.py collectstatic
before_script:
  - "export DATABASE_URL=sqlite:///:memory"
script:
  coverage run manage.py test
after_success:
  coveralls
