language: python
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm --version
  - npm install -g yarn
  - yarn global add gulp-cli
  - yarn install
  - gulp --version
  - gulp build
  - pip install -U pip setuptools wheel
  - pip install -r requirements/local.txt
  - pip install coveralls
  - python manage.py collectstatic --no-input
  - gem install coveralls-lcov
before_script:
  - "export DATABASE_URL=sqlite:///:memory"
script:
  - coverage run manage.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - coveralls-lcov -v -n ./coverage/lcov.info > coverage.json
  - "coveralls --merge=coverage.json"
  - yarn outdated
  - pip list -o
