# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0003_auto_20150812_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='desc_class',
            field=models.TextField(default=b''),
        ),
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together=set([('assessment', 'rating')]),
        ),
    ]
