# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0004_auto_20160105_0402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Assessments'},
        ),
        migrations.AddField(
            model_name='attribute',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
