# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0007_auto_20160107_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='desc_class',
            field=models.TextField(default=b''),
        ),
    ]
