# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0010_measurement_target_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=b'Assessment ID'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=b'Attribute ID'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=256, verbose_name=b'Attribute Name'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=b'Rating ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=b'Tag ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name=b'Tag Name'),
        ),
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=b'Template ID'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name=b'Template Name'),
        ),
    ]
