# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0010_measurement_target_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('short_desc', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(to='measure_mate.Tag')),
            ],
            options={
                'ordering': ['-pk'],
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
