# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0011_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measure_mate.Team'),
        ),
    ]
