# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0012_auto_20160223_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='measure_mate.Team'),
        ),
    ]
