# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0011_auto_20160225_1305'),
        ('measure_mate', '0014_auto_20160224_0207'),
    ]

    operations = [
    ]
