# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0015_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='measure_mate.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=b'Team ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name=b'Team Name'),
        ),
    ]
