# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0017_auto_20160302_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='measure_mate.Team'),
        ),
    ]
