# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0018_auto_20160311_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='desc_class',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
