# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0020_auto_20160314_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='tags',
        ),
    ]
