# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0020_auto_20160314_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='measure_mate.Assessment')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='measure_mate.Measurement')),
            ],
            options={
                'verbose_name_plural': 'Actions',
            },
        ),
    ]
