# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0021_remove_assessment_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('key_metric', models.TextField()),
                ('review_date', models.DateTimeField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='measure_mate.Assessment')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='measure_mate.Measurement')),
            ],
            options={
                'ordering': ['assessment', 'measurement', 'rank'],
                'verbose_name_plural': 'Actions',
            },
        ),
    ]
