# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0021_remove_assessment_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='action',
            field=models.TextField(null=True),
        ),
    ]
