# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0023_auto_20160330_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[(b'TODO', b'To Do'), (b'DONE', b'Done')], default=b'TODO', max_length=128),
        ),
    ]
