# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0024_auto_20160329_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='key_metric',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='measure_mate.Measurement'),
        ),
    ]
