# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0024_assessment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(unique=True, verbose_name=b'Tag Name'),
        ),
    ]
