# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 07:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0025_auto_20160516_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(re.compile(b'[A-Z]'), "Enter a valid 'slug' consisting of lowercase letters, numbers, underscores or hyphens.", b'invalid', True)], verbose_name=b'Tag Name'),
        ),
    ]
