# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0026_auto_20160531_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='tags',
            field=models.ManyToManyField(to='measure_mate.Tag'),
        ),
        migrations.AddField(
            model_name='template',
            name='taggable',
            field=models.BooleanField(default=0),
        ),
    ]
