# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0027_auto_20160720_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='enabled',
            field=models.BooleanField(default=1),
        ),
    ]
