# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0028_template_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='colour',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
