# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 07:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0029_auto_20161018_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(code=b'invalid', inverse_match=True, message="Enter a valid 'slug' consisting of lowercase letters, numbers, underscores or hyphens.", regex=re.compile(b'[A-Z]'))], verbose_name=b'Tag Name'),
        ),
    ]
