# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 02:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0031_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Templates'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='enabled',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='desc',
            field=models.TextField(verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='desc_class',
            field=models.CharField(blank=True, default=b'', max_length=256, verbose_name=b'Description CSS Class'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='rating',
            name='desc',
            field=models.TextField(verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='desc_class',
            field=models.CharField(blank=True, default=b'', max_length=256, verbose_name=b'Description CSS Class'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(code=b'invalid', message="Enter a valid 'slug' consisting of lowercase letters, numbers, underscores or hyphens; starting and ending with letters or numbers.", regex=re.compile(b'^[a-z0-9][a-z0-9_-][a-z0-9]$'))]),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_desc',
            field=models.CharField(max_length=256, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='short_desc',
            field=models.CharField(max_length=256, verbose_name=b'Description'),
        ),
    ]
