# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0033_auto_20161207_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='creator',
        ),
    ]
