# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0034_remove_announcement_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='style',
            field=models.CharField(choices=[(b'Default', b'default'), (b'Primary', b'primary'), (b'Success', b'success'), (b'Info', b'success'), (b'Warning', b'warning'), (b'Danger', b'danger')], default=b'warning', max_length=50),
        ),
    ]
