# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0035_announcement_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='style',
            field=models.CharField(choices=[(b'default', b'Default'), (b'primary', b'Primary'), (b'success', b'Success'), (b'info', b'Success'), (b'warning', b'Warning'), (b'danger', b'Danger')], default=b'warning', max_length=50),
        ),
    ]
