# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0036_auto_20161208_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='enabled',
            field=models.BooleanField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='rank',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rank',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='enabled',
            field=models.BooleanField(db_index=True, default=1),
        ),
    ]
