# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 00:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0037_auto_20161211_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='style',
            field=models.CharField(choices=[('default', 'Default'), ('primary', 'Primary'), ('success', 'Success'), ('info', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='warning', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('DONE', 'Done')], default='TODO', max_length=128),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='desc_class',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Description CSS Class'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='desc_class',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Description CSS Class'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message="Enter a valid 'slug' consisting of lowercase letters, numbers, underscores or hyphens; starting and ending with letters or numbers.", regex=re.compile('^[a-z0-9][a-z0-9_-]*[a-z0-9]$', 32))]),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_desc',
            field=models.CharField(max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='template',
            name='short_desc',
            field=models.CharField(max_length=256, verbose_name='Description'),
        ),
    ]
