# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0039_auto_20170221_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='attribute',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measure_mate.Attribute'),
            preserve_default=False,
        ),
    ]
