# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 06:18
from __future__ import unicode_literals

from django.db import migrations

def populate_attribute(apps, schema_editor):
    Measurement = apps.get_model('measure_mate', 'Measurement')
    for row in Measurement.objects.all():
        row.attribute = row.rating.attribute
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0040_add_attribute_foreign_key'),
    ]

    operations = [
        migrations.RunPython(populate_attribute, reverse_code=migrations.RunPython.noop),            
    ]
