# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0041_populate_attribute_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together=set([('assessment', 'attribute')]),
        ),
    ]
