# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measure_mate', '0044_auto_20170317_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='measure_mate.Template'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='measure_mate.Attribute'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='measure_mate.Rating'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='target_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_measurements', to='measure_mate.Rating'),
        ),
    ]
